### ISSUE TITLE
problem after reset components

### ISSUE THREAD

**Issue by lecocqe** [thomasgermain/pymultiMATIC#87]
hello Thomas,

i hope you're doing well.
my system is stuck. to test, i got the following running dump.py:
```
Trying to connect with user myuser
Login successful
did 0 requests
received 0 responses
Traceback (most recent call last):
  File "./dump.py", line 97, in <module>
    asyncio.get_event_loop().run_until_complete(main(user, passw))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./dump.py", line 86, in main
    print(await manager.set_quick_mode(QuickModes.get('QM_COOLING_FOR_X_DAYS', 2)))
TypeError: get() takes 2 positional arguments but 3 were given
```
do you have an idea ?

thank you in advance

Eric

**Comment by thomasgermain** [comment]
Hello Eric,

I'm doing well thanks :) and you ?

What do you mean by stuck ?

I did some improvement to dump.py, it should work

**Comment by lecocqe** [comment]
here last result:
```
Traceback (most recent call last):
  File "./dump.py", line 27, in <module>
    urls.system_ventilation: {},
AttributeError: module 'pymultimatic.api.urls' has no attribute 'system_ventilation'

```

**Comment by thomasgermain** [comment]
Be sure to be on master branch while testing the dump.
What was the issue in HA ? Do you have any error ?
