### ISSUE TITLE
FACILITY_NOT_COMPATIBLE VR921

### ISSUE THREAD

**Issue by Q1984** [thomasgermain/pymultiMATIC#93]
Hello,

Trying to use the sample script with my VR921, without success. Any advice what am I doing wrong? Thx!

```
Trying to connect with user *redacted*
Traceback (most recent call last):
  File "script.py", line 28, in <module>
    asyncio.get_event_loop().run_until_complete(main(user, passw))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "script.py", line 17, in main
    system =  await manager.get_system()
  File "/usr/local/lib/python3.8/dist-packages/pymultimatic/systemmanager.py", line 165, in get_system
    (facilities, full_system, live_report, hvac_state, gateway_json,) = await asyncio.gather(
  File "/usr/local/lib/python3.8/dist-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymultimatic/systemmanager.py", line 857, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.8/dist-packages/pymultimatic/api/connector.py", line 164, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/*redacted*/systemcontrol/v1, status: 409, response: {"errorCode":"FACILITY_NOT_COMPATIBLE"},payload: None
```

**Comment by thomasgermain** [comment]
Hello,

unfortunately, the VR921 is not supported by the integration
